/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface NameComponent {
    /**
    * Name property
    */
    'name': string;
  }
  interface NameComponentAttributes extends StencilHTMLAttributes {
    /**
    * Name property
    */
    'name'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyComponent': Components.MyComponent;
    'NameComponent': Components.NameComponent;
  }

  interface StencilIntrinsicElements {
    'my-component': Components.MyComponentAttributes;
    'name-component': Components.NameComponentAttributes;
  }


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLNameComponentElement extends Components.NameComponent, HTMLStencilElement {}
  var HTMLNameComponentElement: {
    prototype: HTMLNameComponentElement;
    new (): HTMLNameComponentElement;
  };

  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement
    'name-component': HTMLNameComponentElement
  }

  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'name-component': HTMLNameComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
